eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
    command:
      paas-file:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 1000  #命令执行超时时间，默认1000ms
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 2000
      service-feign:
        connect-timeout: 1000
        read-timeout: 2000
swagger2:
  enable: true
  base-package: com.lmn