server:
  port: 8762

spring:
  application:
    name: service-hi
  sleuth:
    sampler:
      percentage: 1  #链路采集率, 默认为10%
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger2:
  enable: true
  base-package: com.lmn